from __future__ import annotations
import _magnum
from _magnum import Vector3
import attr as attr
from collections import OrderedDict
from collections.abc import MutableMapping
import habitat_sim as habitat_sim
from habitat_sim._ext.habitat_sim_bindings import NavMeshSettings
from habitat_sim._ext.habitat_sim_bindings import PathFinder
from habitat_sim._ext.habitat_sim_bindings import SensorSpec
from habitat_sim._ext.habitat_sim_bindings import SensorType
from habitat_sim._ext.habitat_sim_bindings import Simulator as SimulatorBackend
from habitat_sim._ext.habitat_sim_bindings import SimulatorConfiguration
from habitat_sim.agent.agent import Agent
from habitat_sim.agent.agent import AgentConfiguration
from habitat_sim.agent.agent import AgentState
from habitat_sim.nav.greedy_geodesic_follower import GreedyGeodesicFollower
from habitat_sim.sensors.noise_models import make_sensor_noise_model
from habitat_sim.utils.common import quat_from_angle_axis
import logging
import magnum as mn
import numpy as np
from numpy import ndarray
import posixpath as osp
import time as time
import torch as torch
from torch import Tensor
import typing
from typing import cast
from typing import overload
__all__: list[str] = ['Agent', 'AgentConfiguration', 'AgentState', 'Configuration', 'GreedyGeodesicFollower', 'MutableMapping', 'MutableMapping_T', 'NavMeshSettings', 'OrderedDict', 'PathFinder', 'Sensor', 'SensorSpec', 'SensorType', 'Simulator', 'SimulatorBackend', 'SimulatorConfiguration', 'Tensor', 'Vector3', 'attr', 'cast', 'cuda_enabled', 'habitat_sim', 'logger', 'make_sensor_noise_model', 'mn', 'ndarray', 'np', 'osp', 'overload', 'quat_from_angle_axis', 'time', 'torch']
class Configuration:
    """
    Specifies how to configure the simulator.
    
        :property sim_cfg: The configuration of the backend of the simulator
        :property agents: A list of agent configurations
    
        Ties together a backend config, `sim_cfg` and a list of agent
        configurations `agents`.
        
    """
    __attrs_attrs__: typing.ClassVar[ConfigurationAttributes]  # value = (Attribute(name='sim_cfg', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='sim_cfg'), Attribute(name='agents', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.List[habitat_sim.agent.agent.AgentConfiguration], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='agents'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('sim_cfg', 'agents', '__weakref__')
    def __eq__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __init__(self, sim_cfg: habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration, agents: typing.List[habitat_sim.agent.agent.AgentConfiguration]) -> None:
        """
        Method generated by attrs for class Configuration.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __repr__(self):
        """
        Method generated by attrs for class Configuration.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
class Sensor:
    """
    Wrapper around habitat_sim.Sensor
    
        TODO(MS) define entire Sensor class in python, reducing complexity
        
    """
    def __init__(self, sim: Simulator, agent: habitat_sim.agent.agent.Agent, sensor_id: str) -> None:
        ...
    def close(self) -> None:
        ...
    def draw_observation(self) -> None:
        ...
    def get_observation(self) -> typing.Union[numpy.ndarray, ForwardRef('Tensor')]:
        ...
class Simulator(habitat_sim._ext.habitat_sim_bindings.Simulator):
    """
    The core class of habitat-sim
    
        :property config: configuration for the simulator
    
        The simulator ties together the backend, the agent, controls functions,
        NavMesh collision checking/pathfinding, attribute template management,
        object manipulation, and physics simulation.
        
    """
    __attrs_attrs__: typing.ClassVar[SimulatorAttributes]  # value = (Attribute(name='config', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'habitat_sim.simulator.Configuration'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='config'), Attribute(name='agents', default=Factory(factory=<class 'list'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=typing.List[habitat_sim.agent.agent.Agent], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='agents'), Attribute(name='_num_total_frames', default=0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='num_total_frames'), Attribute(name='_default_agent_id', default=0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='default_agent_id'), Attribute(name='_Simulator__sensors', default=Factory(factory=<class 'list'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=typing.List[typing.Dict[str, ForwardRef('Sensor')]], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='Simulator__sensors'), Attribute(name='_initialized', default=False, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'bool'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='initialized'), Attribute(name='_previous_step_time', default=0.0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='previous_step_time'), Attribute(name='_Simulator__last_state', default=Factory(factory=<class 'dict'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=typing.Dict[int, habitat_sim.agent.agent.AgentState], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='Simulator__last_state'))
    __hash__: typing.ClassVar[None] = None
    _last_state: habitat_sim.agent.agent.AgentState
    @staticmethod
    def _sanitize_config(config: Configuration) -> None:
        ...
    def _Simulator__set_from_config(self, config: Configuration) -> None:
        ...
    def __attrs_post_init__(self) -> None:
        ...
    def __del__(self) -> None:
        ...
    def __enter__(self) -> Simulator:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __exit__(self, exc_type, exc_val, exc_tb):
        ...
    def __ge__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __init__(self, config: Configuration) -> None:
        """
        Method generated by attrs for class Simulator.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __repr__(self):
        """
        Method generated by attrs for class Simulator.
        """
    def _config_agents(self, config: Configuration) -> None:
        ...
    def _config_backend(self, config: Configuration) -> None:
        ...
    def _config_pathfinder(self, config: Configuration) -> None:
        ...
    def _update_simulator_sensors(self, uuid: str, agent_id: int) -> None:
        ...
    def add_sensor(self, sensor_spec: habitat_sim._ext.habitat_sim_bindings.SensorSpec, agent_id: typing.Union[int, NoneType] = None) -> None:
        ...
    def close(self) -> None:
        ...
    def get_agent(self, agent_id: int) -> habitat_sim.agent.agent.Agent:
        ...
    def get_sensor_observations(self, agent_ids: typing.Union[int, typing.List[int]] = 0) -> typing.Union[typing.Dict[str, typing.Union[numpy.ndarray, ForwardRef('Tensor')]], typing.Dict[int, typing.Dict[str, typing.Union[numpy.ndarray, ForwardRef('Tensor')]]]]:
        ...
    def initialize_agent(self, agent_id: int, initial_state: typing.Union[habitat_sim.agent.agent.AgentState, NoneType] = None) -> habitat_sim.agent.agent.Agent:
        ...
    def last_state(self, agent_id: typing.Union[int, NoneType] = None) -> habitat_sim.agent.agent.AgentState:
        ...
    def make_greedy_follower(self, agent_id: typing.Union[int, NoneType] = None, goal_radius: float = None, *, stop_key: typing.Union[typing.Any, NoneType] = None, forward_key: typing.Union[typing.Any, NoneType] = None, left_key: typing.Union[typing.Any, NoneType] = None, right_key: typing.Union[typing.Any, NoneType] = None, fix_thrashing: bool = True, thrashing_threshold: int = 16):
        ...
    def reconfigure(self, config: Configuration) -> None:
        ...
    def reset(self, agent_ids: typing.Union[int, NoneType, typing.List[int]] = None) -> typing.Union[typing.Dict[str, typing.Union[numpy.ndarray, ForwardRef('Tensor')]], typing.Dict[int, typing.Dict[str, typing.Union[numpy.ndarray, ForwardRef('Tensor')]]]]:
        ...
    def reset_agent(self, agent_id: int) -> None:
        ...
    def seed(self, new_seed: int) -> None:
        ...
    def step(self, action: typing.Union[str, int, typing.MutableMapping[int, typing.Union[str, int]]], dt: float = 0.016666666666666666) -> typing.Union[typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]], typing.Dict[int, typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]]]]:
        ...
    def step_filter(self, start_pos: _magnum.Vector3, end_pos: _magnum.Vector3) -> _magnum.Vector3:
        """
        Computes a valid navigable end point given a target translation on the NavMesh.
                Uses the configured sliding flag.
        
                :param start_pos: The valid initial position of a translation.
                :param end_pos: The target end position of a translation.
                
        """
    def step_physics(self, dt: float, scene_id: int = 0) -> None:
        ...
    @property
    def _default_agent(self) -> habitat_sim.agent.agent.Agent:
        ...
    @property
    def _sensors(self) -> typing.Dict[str, ForwardRef('Sensor')]:
        ...
MutableMapping_T: typing._GenericAlias  # value = typing.MutableMapping
_HAS_TORCH: bool = True
cuda_enabled: bool = False
logger: logging.Logger  # value = <Logger /home/vscode/.conda/envs/etpr1-new/lib/python3.8/site-packages/habitat_sim/logging.py (INFO)>
