from __future__ import annotations
import _magnum
from _magnum import Vector3
import attr as attr
from collections import OrderedDict
from collections.abc import MutableMapping
import habitat_sim as habitat_sim
from habitat_sim._ext.habitat_sim_bindings import MetadataMediator
from habitat_sim._ext.habitat_sim_bindings import SensorSpec
from habitat_sim._ext.habitat_sim_bindings import SensorType
from habitat_sim._ext.habitat_sim_bindings import Simulator as SimulatorBackend
from habitat_sim._ext.habitat_sim_bindings import SimulatorConfiguration
from habitat_sim._ext.habitat_sim_bindings.core import LoggingContext
from habitat_sim.agent.agent import Agent
from habitat_sim.agent.agent import AgentConfiguration
from habitat_sim.agent.agent import AgentState
from habitat_sim.nav.greedy_geodesic_follower import GreedyGeodesicFollower
from habitat_sim.sensors.noise_models import make_sensor_noise_model
from habitat_sim.utils.common import quat_from_angle_axis
import logging
import magnum as mn
import numpy as np
from numpy import ndarray
import time as time
import typing
from typing import cast
from typing import overload
__all__: list[str] = ['Agent', 'AgentConfiguration', 'AgentState', 'Configuration', 'GreedyGeodesicFollower', 'LoggingContext', 'MetadataMediator', 'MutableMapping', 'MutableMapping_T', 'ObservationDict', 'OrderedDict', 'Sensor', 'SensorSpec', 'SensorType', 'Simulator', 'SimulatorBackend', 'SimulatorConfiguration', 'Vector3', 'attr', 'cast', 'cuda_enabled', 'habitat_sim', 'logger', 'make_sensor_noise_model', 'mn', 'ndarray', 'np', 'overload', 'quat_from_angle_axis', 'time']
class Configuration:
    """
    Specifies how to configure the simulator.
    
        :property sim_cfg: The configuration of the backend of the simulator
        :property agents: A list of agent configurations
        :property metadata_mediator: (optional) The metadata mediator to build the simulator from.
    
        Ties together a backend config, `sim_cfg` and a list of agent
        configurations `agents`.
        
    """
    __attrs_attrs__: typing.ClassVar[attr._make.ConfigurationAttributes]  # value = (Attribute(name='sim_cfg', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='sim_cfg'), Attribute(name='agents', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.List[habitat_sim.agent.agent.AgentConfiguration], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='agents'), Attribute(name='metadata_mediator', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Optional[habitat_sim._ext.habitat_sim_bindings.MetadataMediator], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='metadata_mediator'), Attribute(name='enable_batch_renderer', default=False, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'bool'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='enable_batch_renderer'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('sim_cfg', 'agents', 'metadata_mediator', 'enable_batch_renderer', '__weakref__')
    def __eq__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __init__(self, sim_cfg: habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration, agents: typing.List[habitat_sim.agent.agent.AgentConfiguration], metadata_mediator: typing.Optional[habitat_sim._ext.habitat_sim_bindings.MetadataMediator] = None, enable_batch_renderer: bool = False) -> None:
        """
        Method generated by attrs for class Configuration.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class Configuration.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class Configuration.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
class Sensor:
    """
    Wrapper around habitat_sim.Sensor
    
        TODO(MS) define entire Sensor class in python, reducing complexity
        
    """
    buffer: typing.ClassVar[typing._UnionGenericAlias]  # value = typing.Union[numpy.ndarray, ForwardRef('Tensor')]
    def __init__(self, sim: Simulator, agent: habitat_sim.agent.agent.Agent, sensor_id: str) -> None:
        ...
    def _draw_observation_async(self) -> None:
        ...
    def _get_audio_observation(self) -> typing.Union[numpy.ndarray, ForwardRef('Tensor')]:
        ...
    def _get_observation_async(self) -> typing.Union[numpy.ndarray, ForwardRef('Tensor')]:
        ...
    def _initialize_sensor(self):
        """
        
                Allocate buffers and initialize noise model in preparation for rendering.
                
        """
    def close(self) -> None:
        ...
    def draw_observation(self) -> None:
        ...
    def get_observation(self) -> typing.Union[numpy.ndarray, ForwardRef('Tensor')]:
        ...
class Simulator(habitat_sim._ext.habitat_sim_bindings.Simulator):
    """
    The core class of habitat-sim
    
        :property config: configuration for the simulator
    
        The simulator ties together the backend, the agent, controls functions,
        NavMesh collision checking/pathfinding, attribute template management,
        object manipulation, and physics simulation.
        
    """
    __attrs_attrs__: typing.ClassVar[attr._make.SimulatorAttributes]  # value = (Attribute(name='config', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'habitat_sim.simulator.Configuration'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='config'), Attribute(name='agents', default=Factory(factory=<class 'list'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=typing.List[habitat_sim.agent.agent.Agent], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='agents'), Attribute(name='_num_total_frames', default=0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='num_total_frames'), Attribute(name='_default_agent_id', default=0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='default_agent_id'), Attribute(name='_Simulator__sensors', default=Factory(factory=<class 'list'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=typing.List[typing.Dict[str, ForwardRef('Sensor')]], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='Simulator__sensors'), Attribute(name='_initialized', default=False, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'bool'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='initialized'), Attribute(name='_previous_step_time', default=0.0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='previous_step_time'), Attribute(name='_async_draw_agent_ids', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[int, typing.List[int], NoneType], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='async_draw_agent_ids'), Attribute(name='_Simulator__last_state', default=Factory(factory=<class 'dict'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=False, metadata=mappingproxy({}), type=typing.Dict[int, habitat_sim.agent.agent.AgentState], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='Simulator__last_state'))
    __hash__: typing.ClassVar[None] = None
    _last_state: habitat_sim.agent.agent.AgentState
    @staticmethod
    def _sanitize_config(config: Configuration) -> None:
        ...
    def _Simulator__set_from_config(self, config: Configuration) -> None:
        ...
    def __attrs_post_init__(self) -> None:
        ...
    def __del__(self) -> None:
        ...
    def __enter__(self) -> Simulator:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __exit__(self, exc_type, exc_val, exc_tb):
        ...
    def __ge__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __init__(self, config: Configuration, async_draw_agent_ids: typing.Union[int, typing.List[int], NoneType] = None) -> None:
        """
        Method generated by attrs for class Simulator.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class Simulator.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class Simulator.
        """
    def _config_agents(self, config: Configuration) -> None:
        ...
    def _config_backend(self, config: Configuration) -> None:
        ...
    def _config_pathfinder(self, config: Configuration) -> None:
        ...
    def _update_simulator_sensors(self, uuid: str, agent_id: int) -> None:
        ...
    def add_sensor(self, sensor_spec: habitat_sim._ext.habitat_sim_bindings.SensorSpec, agent_id: typing.Optional[int] = None) -> None:
        ...
    def close(self, destroy: bool = True) -> None:
        """
        Close the simulator instance.
        
                :param destroy: Whether or not to force the OpenGL context to be
                    destroyed if async rendering was used.  If async rendering wasn't used,
                    this has no effect.
                
        """
    def get_agent(self, agent_id: int) -> habitat_sim.agent.agent.Agent:
        ...
    def get_sensor_observations(self, agent_ids: typing.Union[int, typing.List[int]] = 0) -> typing.Union[typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]], typing.Dict[int, typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]]]]:
        ...
    def get_sensor_observations_async_finish(self) -> typing.Union[typing.Dict[str, typing.Union[numpy.ndarray, ForwardRef('Tensor')]], typing.Dict[int, typing.Dict[str, typing.Union[numpy.ndarray, ForwardRef('Tensor')]]]]:
        ...
    def initialize_agent(self, agent_id: int, initial_state: typing.Optional[habitat_sim.agent.agent.AgentState] = None) -> habitat_sim.agent.agent.Agent:
        ...
    def last_state(self, agent_id: typing.Optional[int] = None) -> habitat_sim.agent.agent.AgentState:
        ...
    def make_greedy_follower(self, agent_id: typing.Optional[int] = None, goal_radius: typing.Optional[float] = None, *, stop_key: typing.Optional[typing.Any] = None, forward_key: typing.Optional[typing.Any] = None, left_key: typing.Optional[typing.Any] = None, right_key: typing.Optional[typing.Any] = None, fix_thrashing: bool = True, thrashing_threshold: int = 16):
        ...
    def reconfigure(self, config: Configuration) -> None:
        ...
    def reset(self, agent_ids: typing.Union[int, NoneType, typing.List[int]] = None) -> typing.Union[typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]], typing.Dict[int, typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]]]]:
        """
        
                Reset the simulation state including the state of all physics objects, agents, and the default light setup.
                Sets the world time to 0.0, changes the physical state of all objects back to their initial states.
                Does not invalidate existing ManagedObject wrappers.
                Does not add or remove object instances.
                Only changes motion_type when scene_instance specified a motion type.
        
                :param agent_ids: An optional list of agent ids for which to return the sensor observations. If none is provide, default agent is used.
        
                :return: Sensor observations in the reset state.
                
        """
    def reset_agent(self, agent_id: int) -> None:
        ...
    def seed(self, new_seed: int) -> None:
        ...
    def start_async_render(self, agent_ids: typing.Union[int, typing.List[int]] = 0):
        ...
    def start_async_render_and_step_physics(self, dt: float, agent_ids: typing.Union[int, typing.List[int]] = 0):
        ...
    def step(self, action: typing.Union[str, int, typing.MutableMapping[int, typing.Union[str, int]]], dt: float = 0.016666666666666666) -> typing.Union[typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]], typing.Dict[int, typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]]]]:
        ...
    def step_filter(self, start_pos: _magnum.Vector3, end_pos: _magnum.Vector3) -> _magnum.Vector3:
        """
        Computes a valid navigable end point given a target translation on the NavMesh.
                Uses the configured sliding flag.
        
                :param start_pos: The valid initial position of a translation.
                :param end_pos: The target end position of a translation.
                
        """
    def step_physics(self, dt: float) -> None:
        ...
    @property
    def _default_agent(self) -> habitat_sim.agent.agent.Agent:
        ...
    @property
    def _sensors(self) -> typing.Dict[str, ForwardRef('Sensor')]:
        ...
MutableMapping_T: typing._SpecialGenericAlias  # value = typing.MutableMapping
ObservationDict: typing._GenericAlias  # value = typing.Dict[str, typing.Union[bool, numpy.ndarray, ForwardRef('Tensor')]]
_HAS_TORCH: bool = False
cuda_enabled: bool = False
logger: logging.Logger  # value = <Logger /home/vscode/.conda/envs/prior/lib/python3.9/site-packages/habitat_sim-0.3.3-py3.9-linux-x86_64.egg/habitat_sim/logging.py (ERROR)>
