from __future__ import annotations
import abc as abc
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
from habitat_sim import bindings as hsim
import typing
__all__: list[str] = ['ActuationSpec', 'SceneNodeControl', 'abc', 'attr', 'hsim']
class ActuationSpec:
    """
    Struct to hold parameters for the default actions
    
        :property amount: The amount the control moves the scene node by
        :property constraint: A constraint on the actuation.  Currently only applies to the
            maximum amount the agent can lookup or loopdown
    
        The default actions only have one parameters, the amount
        they move the scene node by, however other actions may have any number of
        parameters and can define different structs to hold those parameters
        
    """
    __attrs_attrs__: typing.ClassVar[ActuationSpecAttributes]  # value = (Attribute(name='amount', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='amount'), Attribute(name='constraint', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[float, NoneType], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='constraint'))
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, other):
        """
        Method generated by attrs for class ActuationSpec.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class ActuationSpec.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class ActuationSpec.
        """
    def __init__(self, amount: float, constraint: typing.Union[float, NoneType] = None) -> None:
        """
        Method generated by attrs for class ActuationSpec.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class ActuationSpec.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class ActuationSpec.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class ActuationSpec.
        """
    def __repr__(self):
        """
        Method generated by attrs for class ActuationSpec.
        """
class SceneNodeControl(abc.ABC):
    """
    Base class for all controls
    
        :property body_action: Whether or not the control function manipulates the
            agents body or the sensors
    
        Control classes are used to implement agent actions.  Any new control
        must subclass this class.
    
        See ``default_controls.py`` for an example of adding new actions. (Note
        that this can be done *outside* the core `habitat_sim` codebase in exactly
        the same way.)
    
        See ``examples/tutorials/new_actions.py`` for an example of how to add new actions
        *outside* the core habitat_sim package.
        
    """
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset({'__call__'})
    __attrs_attrs__: typing.ClassVar[SceneNodeControlAttributes]  # value = (Attribute(name='body_action', default=False, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'bool'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='body_action'),)
    __hash__: typing.ClassVar[None] = None
    _abc_impl: typing.ClassVar[_abc_data]  # value = <_abc_data object>
    def __call__(self, scene_node: habitat_sim._ext.habitat_sim_bindings.SceneNode, acutation_spec: ActuationSpec) -> None:
        """
        Abstract method to be overridden to implement the control
        
                :param scene_node: The scene node to control
                :param acutation_spec: Struct holding any parameters of the control
                
        """
    def __eq__(self, other):
        """
        Method generated by attrs for class SceneNodeControl.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class SceneNodeControl.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class SceneNodeControl.
        """
    def __init__(self, body_action: bool = False) -> None:
        """
        Method generated by attrs for class SceneNodeControl.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class SceneNodeControl.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class SceneNodeControl.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class SceneNodeControl.
        """
    def __repr__(self):
        """
        Method generated by attrs for class SceneNodeControl.
        """
