from __future__ import annotations
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
import habitat_sim.agent.controls.controls
from habitat_sim.agent.controls.controls import ActuationSpec
from habitat_sim import bindings as hsim
import habitat_sim.registry
import magnum as mn
import numpy as np
import quaternion as quaternion
import typing
__all__: list[str] = ['ActuationSpec', 'EPS', 'ObjectControls', 'attr', 'hsim', 'mn', 'np', 'quaternion', 'registry']
class ObjectControls:
    """
    Used to implement actions
    
        :property move_filter_fn: A function that is applied after actions to
            handle collisions
        
    """
    __attrs_attrs__: typing.ClassVar[ObjectControlsAttributes]  # value = (Attribute(name='move_filter_fn', default=<function _noop_filter at 0x7fe9cb6a5e50>, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Callable[[typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]], typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]]], typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]]], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='move_filter_fn'),)
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def is_body_action(action_name: str):
        """
        Checks to see if :p:`action_name` is a body action
        
                :param action_name: Name of the action
                
        """
    def __call__(self, obj: habitat_sim._ext.habitat_sim_bindings.SceneNode, action_name: str, actuation_spec: habitat_sim.agent.controls.controls.ActuationSpec, apply_filter: bool = True):
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class ObjectControls.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class ObjectControls.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class ObjectControls.
        """
    def __init__(self, move_filter_fn: typing.Callable[[typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]], typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]]], typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]]] = _noop_filter) -> None:
        """
        Method generated by attrs for class ObjectControls.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class ObjectControls.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class ObjectControls.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class ObjectControls.
        """
    def __repr__(self):
        """
        Method generated by attrs for class ObjectControls.
        """
    def action(self, obj: habitat_sim._ext.habitat_sim_bindings.SceneNode, action_name: str, actuation_spec: habitat_sim.agent.controls.controls.ActuationSpec, apply_filter: bool = True) -> bool:
        """
        Performs the action specified by :p:`action_name` on the object
        
                :param obj: `scene.SceneNode` to perform the action on
                :param action_name: Name of the action. Used to query the
                    `registry` to retrieve the function which implements
                    this action
                :param actuation_spec: Specifies the parameters needed by the function
                :param apply_filter: Whether or not to apply the `move_filter_fn`
                    after the action
                :return: Whether or not the action taken resulted in a collision
                
        """
def _noop_filter(start: typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]], end: typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]]) -> typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]]:
    ...
EPS: float = 1e-05
_3d_point: typing._GenericAlias  # value = typing.Union[numpy.ndarray, _magnum.Vector3, typing.Tuple[float, float, float]]
registry: habitat_sim.registry._Registry  # value = <habitat_sim.registry._Registry object>
