name: etpr1-new
channels:
  - aihabitat
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip<24.1
  - setuptools<=69.5.1
  - numpy=1.23.5
  - scipy
  - matplotlib
  - pillow=8.3.2
  - imageio
  - imageio-ffmpeg
  - ipykernel=5.5.5
  - ipython
  - jupyter_client=5.3.4
  - numba
  - quaternion
  - tqdm
  - lerc=3.0
  - habitat-sim=0.1.7=py3.8_headless_linux_856d4b08c1a2632626bf0d205bf46471a99502b7
  - habitat-sim-mutex=1.0=headless_nobullet
variables:
  LD_LIBRARY_PATH: /home/vscode/.conda/envs/etpr1-new/lib
