# stubs/_magnum.pyi
# Type stub generated using copilot
"""Type stubs for _magnum (magnum's internal C++ module)"""
from __future__ import annotations
from typing import Any, overload, Sequence

class Vector2:
    x: float
    y: float
    def __init__(self, x: float = 0, y: float = 0) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...

class Vector3:
    x:  float
    y: float
    z: float
    def __init__(self, x: float = 0, y: float = 0, z: float = 0) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index:  int, value: float) -> None: ...

class Vector4:
    x: float
    y:  float
    z: float
    w: float
    def __init__(self, x: float = 0, y: float = 0, z: float = 0, w: float = 0) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...

class Vector2i:
    x: int
    y: int
    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    def __getitem__(self, index:  int) -> int: ...

class Vector3i:
    x: int
    y: int
    z: int
    def __init__(self, x: int = 0, y: int = 0, z: int = 0) -> None: ...
    def __getitem__(self, index:  int) -> int: ...

class Vector4i:
    x:  int
    y: int
    z: int
    w: int
    def __init__(self, x: int = 0, y: int = 0, z:  int = 0, w: int = 0) -> None: ...
    def __getitem__(self, index: int) -> int: ...

class Vector2ui:
    x: int
    y: int
    def __init__(self, x: int = 0, y: int = 0) -> None: ...

class Vector3ui:
    x: int
    y: int
    z: int
    def __init__(self, x: int = 0, y: int = 0, z: int = 0) -> None: ...

class Vector4ui:
    x: int
    y: int
    z: int
    w: int
    def __init__(self, x: int = 0, y:  int = 0, z: int = 0, w: int = 0) -> None: ...

class Vector2d:
    x: float
    y: float
    def __init__(self, x: float = 0, y:  float = 0) -> None: ...

class Vector3d:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0, y: float = 0, z: float = 0) -> None: ...

class Vector4d:
    x: float
    y: float
    z: float
    w: float
    def __init__(self, x: float = 0, y:  float = 0, z: float = 0, w: float = 0) -> None: ...

class Matrix3:
    def __init__(self) -> None: ...
    def __matmul__(self, other: Matrix3) -> Matrix3: ...

class Matrix4:
    def __init__(self) -> None: ...
    def __matmul__(self, other: Matrix4) -> Matrix4: ...
    @staticmethod
    def translation(vector: Vector3) -> Matrix4: ...
    @staticmethod
    def scaling(vector: Vector3) -> Matrix4: ...
    @staticmethod
    def rotation(angle:  Rad, axis: Vector3) -> Matrix4: ...

class Matrix3d:
    def __init__(self) -> None: ...

class Matrix4d:
    def __init__(self) -> None: ...

class Quaternion:
    def __init__(self, vector: Vector3 = ..., scalar: float = ...) -> None: ...
    @staticmethod
    def rotation(angle: Rad, axis: Vector3) -> Quaternion: ...

class Quaterniond:
    def __init__(self) -> None: ...

class Color3:
    r: float
    g: float
    b: float
    def __init__(self, r: float = 0, g: float = 0, b: float = 0) -> None: ...

class Color4:
    r: float
    g: float
    b:  float
    a: float
    def __init__(self, r:  float = 0, g: float = 0, b: float = 0, a: float = 1) -> None: ...

class Rad:
    def __init__(self, value: float = 0) -> None: ...
    def __float__(self) -> float: ...

class Deg:
    def __init__(self, value: float = 0) -> None: ...
    def __float__(self) -> float: ...

class Range1D:
    min: float
    max: float
    def __init__(self, min: float = 0, max:  float = 0) -> None: ...

class Range2D:
    min: Vector2
    max: Vector2
    def __init__(self, min: Vector2 = ..., max: Vector2 = ...) -> None: ...

class Range3D:
    min: Vector3
    max: Vector3
    def __init__(self, min: Vector3 = ..., max: Vector3 = ...) -> None: ...

class Range1Di:
    min: int
    max: int
    def __init__(self, min: int = 0, max: int = 0) -> None: ...

class Range2Di:
    def __init__(self) -> None: ...

class Range3Di:
    def __init__(self) -> None: ...

class Range1Dd:
    def __init__(self) -> None: ...

class Range2Dd:
    def __init__(self) -> None: ...

class Range3Dd:
    def __init__(self) -> None: ...

# Add more classes as needed based on what you actually use
class BitVector2:  ...
class BitVector3: ...
class BitVector4: ...
class Matrix2x2: ...
class Matrix2x3: ...
class Matrix2x4: ...
class Matrix3x2: ...
class Matrix3x3: ...
class Matrix3x4: ...
class Matrix4x2: ...
class Matrix4x3: ...
class Matrix4x4: ...
class Matrix2x2d: ...
class Matrix2x3d: ...
class Matrix2x4d: ...
class Matrix3x2d: ...
class Matrix3x3d: ...
class Matrix3x4d:  ...
class Matrix4x2d: ...
class Matrix4x3d: ...
class Matrix4x4d: ...

class PixelFormat:  ...
class PixelStorage: ...
class CompressedPixelFormat: ...
class MeshPrimitive: ...
class MeshIndexType: ...
class VertexFormat: ...
class SamplerFilter: ...
class SamplerMipmap: ...
class SamplerWrapping: ...

class Image1D: ...
class Image2D: ...
class Image3D:  ...
class CompressedImage1D: ...
class CompressedImage2D: ...
class CompressedImage3D: ...
class ImageView1D: ...
class ImageView2D: ...
class ImageView3D: ...
class MutableImageView1D:  ...
class MutableImageView2D: ...
class MutableImageView3D: ...
class CompressedImageView1D: ...
class CompressedImageView2D: ...
class CompressedImageView3D: ...
class MutableCompressedImageView1D: ...
class MutableCompressedImageView2D: ...
class MutableCompressedImageView3D: ...
