"""Rebuild $OUT/task2_report.md from the per-step fragments in $OUT/md (run after every step)."""

from __future__ import annotations

import datetime as dt
import socket

from common import out_dir

ORDER = [
    ("T2.0", "## T2.0 数据切换"),
    ("T2.1", "## T2.1 k 匹配"),
    ("T2.2", "## T2.2 oracle"),
    ("T2.3", "## T2.3 GT 回放自检"),
    ("T2.4", "## T2.4 预算表"),
    ("T2.5", "## T2.5 误报率表与选定的 v0 参数"),
    ("T2.6", "## T2.6（可选）"),
]


def main() -> None:
    md = out_dir() / "md"
    parts = [
        "# Task 2 Report",
        "",
        f"generated by tools/02_oracles/run_task2.sh on {socket.gethostname()}, last assembled {dt.datetime.now():%Y-%m-%d %H:%M:%S}",
        "",
    ]
    status = md / "status.txt"
    if status.exists():
        parts += [
            "| step | status | finished |",
            "|---|---|---|",
            *[
                f"| {' | '.join(line.split(chr(9)))} |"
                for line in status.read_text().splitlines()
                if line.strip()
            ],
            "",
        ]
    for step, heading in ORDER:
        f = md / f"{step}.md"
        parts += [
            f.read_text().rstrip() if f.exists() else f"{heading}\n\n(not run yet)",
            "",
        ]
    parts += ["## 问题与需要人决定的事", ""]
    issues = md / "issues.txt"
    lines = [
        x
        for x in (issues.read_text().splitlines() if issues.exists() else [])
        if x.strip()
    ]
    parts += [f"- {x}" for x in dict.fromkeys(lines)] or [
        "- (none recorded by the scripts)"
    ]
    (out_dir() / "task2_report.md").write_text("\n".join(parts) + "\n")


if __name__ == "__main__":
    main()
