"""Rebuild $OUT3/task3_report.md from the per-step fragments in $OUT3/md (run after every step).

Section order follows the task book's report structure. A step may be split into sub-fragments
(T3.7a.md, T3.7b.md, T3.7c.md), which are concatenated under the step's heading. Steps the human runs by
hand (T3.1-T3.5, T3.7a/c) show "(not run yet)" until their fragment exists.
"""

from __future__ import annotations

import datetime as dt
import socket

import t3common as t3

ORDER: list[tuple[str, str, tuple[str, ...]]] = [
    (
        "T3.0",
        "## T3.0 修正：单调率 / 终点命中率 / 类型分布 / 预算表 / 误报率 / offtrack episode 列表",
        ("T3.0",),
    ),
    (
        "T3.4",
        "## T3.4 代码地图摘要（全文见 mip_code_map.md）：工具返回能否带图、会话与上下文、拒绝 step 的可行性",
        ("T3.4",),
    ),
    (
        "T3.5",
        "## T3.5 oracle 实现：配置、改动文件、各条件 dry-run 截取、none 与 bareES 一致性证明、单测",
        ("T3.5",),
    ),
    (
        "T3.1",
        "## T3.1 codex 安装与登录：版本、钉死方式、验证结果、codex + fake 结果",
        ("T3.1",),
    ),
    ("T3.2", "## T3.2 单集：指标、token、调用数、时间、是否限流", ("T3.2",)),
    (
        "T3.3",
        "## T3.3 20 集基线 + 3 集冒烟：指标表、逐集 end_reason / distance、限流与吞吐、冒烟截取",
        ("T3.3",),
    ),
    (
        "T3.6",
        "## T3.6 O-承诺：参数扫描误报率表、选定参数、MP3D 语义标注有无",
        ("T3.6",),
    ),
    (
        "T3.7",
        "## T3.7 规则 ROC / 合成召回 / 回溯反放：三张表与结论",
        ("T3.7a", "T3.7b", "T3.7c"),
    ),
]


def main() -> None:
    md = t3.out3_dir() / "md"
    parts = [
        "# Task 3 Report",
        "",
        (
            f"generated by tools/03_codex_baseline_oracle/run_task3.sh on {socket.gethostname()}, "
            f"last assembled {dt.datetime.now(dt.timezone.utc).astimezone():%Y-%m-%d %H:%M:%S %Z}"
        ),
        "",
    ]
    status = md / "status.txt"
    if status.exists():
        parts += [
            "| step | status | finished |",
            "|---|---|---|",
            *[
                f"| {' | '.join(line.split(chr(9)))} |"
                for line in status.read_text(encoding="utf-8").splitlines()
                if line.strip()
            ],
            "",
        ]
    for _step, heading, frags in ORDER:
        found = [md / f"{f}.md" for f in frags if (md / f"{f}.md").exists()]
        if not found:
            parts += [f"{heading}\n\n(not run yet)", ""]
            continue
        if len(frags) > 1:
            parts += [heading, ""]
        for f in found:
            parts += [f.read_text(encoding="utf-8").rstrip(), ""]
    parts += ["## 问题与需要人决定的事", ""]
    issues = md / "issues.txt"
    lines = [
        x
        for x in (
            issues.read_text(encoding="utf-8").splitlines() if issues.exists() else []
        )
        if x.strip()
    ]
    parts += [f"- {x}" for x in dict.fromkeys(lines)] or [
        "- (none recorded by the scripts)"
    ]
    (t3.out3_dir() / "task3_report.md").write_text(
        "\n".join(parts) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
