from __future__ import annotations
import _magnum.scenegraph
import attr as attr
import habitat_sim as habitat_sim
from habitat_sim._ext.habitat_sim_bindings import SceneNode
from habitat_sim.agent.controls.controls import ActuationSpec
from habitat_sim.agent.controls.object_controls import ObjectControls
from habitat_sim import bindings as hsim
from habitat_sim.sensors.sensor_suite import SensorSuite
from habitat_sim.utils.common import quat_from_coeffs
from habitat_sim.utils.common import quat_from_magnum
from habitat_sim.utils.common import quat_rotate_vector
from habitat_sim.utils.common import quat_to_magnum
from habitat_sim.utils.validators import NoAttrValidationContext
from habitat_sim.utils.validators import all_is_finite
from habitat_sim.utils.validators import is_unit_length
from habitat_sim.utils.validators import value_is_validated
import magnum as mn
import numpy as np
import numpy
import quaternion as qt
import quaternion
import typing
__all__: list = ['ActionSpec', 'SixDOFPose', 'AgentState', 'AgentConfiguration', 'Agent']
class ActionSpec:
    """
    Defines how a specific action is implemented
    
        :property name: Name of the function implementing the action in the
            `registry`
        :property actuation: Arguments that will be passed to the function
        
    """
    __attrs_attrs__: typing.ClassVar[attr._make.ActionSpecAttributes]  # value = (Attribute(name='name', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='name'), Attribute(name='actuation', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Optional[habitat_sim.agent.controls.controls.ActuationSpec], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='actuation'))
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, other):
        """
        Method generated by attrs for class ActionSpec.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class ActionSpec.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class ActionSpec.
        """
    def __init__(self, name: str, actuation: typing.Optional[habitat_sim.agent.controls.controls.ActuationSpec] = None) -> None:
        """
        Method generated by attrs for class ActionSpec.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class ActionSpec.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class ActionSpec.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class ActionSpec.
        """
class Agent:
    """
    Implements an agent with multiple sensors
    
        :property agent_config: The configuration of the agent
    
        .. block-warning:: Warning
    
            Agents are given controls over a node in the scene graph, but do
            **not** own this node. This means that errors will occur if the owner
            of the scene graph is deallocated. Generally the owner of the scene
            graph is the Simulator.
    
            If you'd like to have an agent to control without loading up the
            simulator, see unit tests for the agent in ``tests/test_agent.py``. We
            recommend letting the simulator create the agent and own the scene
            graph in almost all cases. Using the scene graph in python is dangerous
            due to differences in c++ and python memory management.
        
    """
    __attrs_attrs__: typing.ClassVar[attr._make.AgentAttributes]  # value = (Attribute(name='agent_config', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'habitat_sim.agent.agent.AgentConfiguration'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='agent_config'), Attribute(name='_sensors', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'habitat_sim.sensors.sensor_suite.SensorSuite'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='sensors'), Attribute(name='controls', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'habitat_sim.agent.controls.object_controls.ObjectControls'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='controls'), Attribute(name='body', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class '_magnum.scenegraph.AbstractFeature3D'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='body'))
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def get_state(*args, **kwds) -> AgentState:
        ...
    def __attrs_init__(self, agent_config: AgentConfiguration, sensors: habitat_sim.sensors.sensor_suite.SensorSuite, controls: habitat_sim.agent.controls.object_controls.ObjectControls, body: _magnum.scenegraph.AbstractFeature3D) -> None:
        """
        Method generated by attrs for class Agent.
        """
    def __eq__(self, other):
        """
        Method generated by attrs for class Agent.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class Agent.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class Agent.
        """
    def __init__(self, scene_node: habitat_sim._ext.habitat_sim_bindings.SceneNode, agent_config: typing.Optional[habitat_sim.agent.agent.AgentConfiguration] = None, _sensors: typing.Optional[habitat_sim.sensors.sensor_suite.SensorSuite] = None, controls: typing.Optional[habitat_sim.agent.controls.object_controls.ObjectControls] = None) -> None:
        ...
    def __le__(self, other):
        """
        Method generated by attrs for class Agent.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class Agent.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class Agent.
        """
    def _add_sensor(self, spec: habitat_sim._ext.habitat_sim_bindings.SensorSpec, modify_agent_config: bool = True) -> None:
        ...
    def act(self, action_id: typing.Any) -> bool:
        """
        Take the action specified by action_id
        
                :param action_id: ID of the action. Retreives the action from
                    `agent_config.action_space <AgentConfiguration.action_space>`
                :return: Whether or not the action taken resulted in a collision
                
        """
    def close(self) -> None:
        ...
    def reconfigure(self, agent_config: AgentConfiguration, reconfigure_sensors: bool = True) -> None:
        """
        Re-create the agent with a new configuration
        
                :param agent_config: New config
                :param reconfigure_sensors: Whether or not to also reconfigure the
                    sensors. There are specific cases where :py:`False` makes sense,
                    but most cases are covered by :py:`True`.
                
        """
    def set_state(self, state: AgentState, reset_sensors: bool = True, infer_sensor_states: bool = True, is_initial: bool = False) -> None:
        """
        Sets the agents state
        
                :param state: The state to set the agent to
                :param reset_sensors: Whether or not to reset the sensors to their
                    default intrinsic/extrinsic parameters before setting their extrinsic state.
                :param infer_sensor_states: Whether or not to infer the location of sensors based on
                    the new location of the agent base state.
                :param is_initial: Whether this state is the initial state of the
                    agent in the scene. Used for resetting the agent at a later time
        
                Setting ``reset_sensors`` to :py:`False`
                allows the agent base state to be moved and the new
                sensor locations inferred without changing the configuration of the sensors
                with respect to the base state of the agent.
        
                Setting ``infer_sensor_states``
                to :py:`False` is useful if you'd like to directly control
                the state of a sensor instead of moving the agent.
        
                
        """
    @property
    def scene_node(self) -> habitat_sim._ext.habitat_sim_bindings.SceneNode:
        ...
    @property
    def state(self):
        """
        Get/set the agent's state.
        
                Getting the state is equivalent to :ref:`get_state`
        
                Setting the state is equivalent calling :ref:`set_state`
                and only providing the state.
                
        """
    @state.setter
    def state(self, new_state: AgentState):
        ...
class AgentConfiguration:
    __attrs_attrs__: typing.ClassVar[attr._make.AgentConfigurationAttributes]  # value = (Attribute(name='height', default=1.5, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='height'), Attribute(name='radius', default=0.1, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='radius'), Attribute(name='sensor_specifications', default=Factory(factory=<class 'list'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.List[habitat_sim._ext.habitat_sim_bindings.SensorSpec], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='sensor_specifications'), Attribute(name='action_space', default=Factory(factory=<function _default_action_space at 0x7f4272fc7b80>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Dict[typing.Any, habitat_sim.agent.agent.ActionSpec], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='action_space'), Attribute(name='body_type', default='cylinder', validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='body_type'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('height', 'radius', 'sensor_specifications', 'action_space', 'body_type', '__weakref__')
    def __eq__(self, other):
        """
        Method generated by attrs for class AgentConfiguration.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class AgentConfiguration.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class AgentConfiguration.
        """
    def __init__(self, height: float = 1.5, radius: float = 0.1, sensor_specifications: typing.List[habitat_sim._ext.habitat_sim_bindings.SensorSpec] = ..., action_space: typing.Dict[typing.Any, habitat_sim.agent.agent.ActionSpec] = ..., body_type: str = 'cylinder') -> None:
        """
        Method generated by attrs for class AgentConfiguration.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class AgentConfiguration.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class AgentConfiguration.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class AgentConfiguration.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
class AgentState:
    __attrs_attrs__: typing.ClassVar[attr._make.AgentStateAttributes]  # value = (Attribute(name='position', default=Factory(factory=<function _triple_zero at 0x7f3e206c1820>, takes_self=False), validator=<function all_is_finite at 0x7f3e21e8b670>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'numpy.ndarray'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='position'), Attribute(name='rotation', default=Factory(factory=<function _default_quaternion at 0x7f3e206c18b0>, takes_self=False), validator=<function is_unit_length at 0x7f3e21e8bee0>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[quaternion.quaternion, typing.List, numpy.ndarray], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='rotation'), Attribute(name='sensor_states', default=Factory(factory=<class 'dict'>, takes_self=False), validator=<deep_mapping validator for objects mapping <instance_of validator for type <class 'str'>> to <function value_is_validated at 0x7f3e21e8bf70>>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Dict[str, habitat_sim.agent.agent.SixDOFPose], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='sensor_states'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('position', 'rotation', 'sensor_states', '__weakref__')
    def __eq__(self, other):
        """
        Method generated by attrs for class AgentState.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class AgentState.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class AgentState.
        """
    def __init__(self, position: numpy.ndarray = ..., rotation: typing.Union[quaternion.quaternion, typing.List, numpy.ndarray] = ..., sensor_states: typing.Dict[str, habitat_sim.agent.agent.SixDOFPose] = ...) -> None:
        """
        Method generated by attrs for class AgentState.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class AgentState.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class AgentState.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class AgentState.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
class SixDOFPose:
    """
    Specifies a position with 6 degrees of freedom
    
        :property position: xyz position
        :property rotation: unit quaternion rotation
        
    """
    __attrs_attrs__: typing.ClassVar[attr._make.SixDOFPoseAttributes]  # value = (Attribute(name='position', default=Factory(factory=<function _triple_zero at 0x7f3e206c1820>, takes_self=False), validator=<function all_is_finite at 0x7f3e21e8b670>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'numpy.ndarray'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='position'), Attribute(name='rotation', default=Factory(factory=<function _default_quaternion at 0x7f3e206c18b0>, takes_self=False), validator=<function is_unit_length at 0x7f3e21e8bee0>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[quaternion.quaternion, typing.List], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='rotation'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('position', 'rotation', '__weakref__')
    def __eq__(self, other):
        """
        Method generated by attrs for class SixDOFPose.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class SixDOFPose.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class SixDOFPose.
        """
    def __init__(self, position: numpy.ndarray = ..., rotation: typing.Union[quaternion.quaternion, typing.List] = ...) -> None:
        """
        Method generated by attrs for class SixDOFPose.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class SixDOFPose.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class SixDOFPose.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class SixDOFPose.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
def _default_action_space() -> typing.Dict[str, habitat_sim.agent.agent.ActionSpec]:
    ...
def _default_quaternion() -> quaternion.quaternion:
    ...
def _triple_zero() -> numpy.ndarray:
    ...
