from __future__ import annotations
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
from habitat_sim._ext.habitat_sim_bindings import SensorType
import habitat_sim.registry
import habitat_sim.sensors.noise_models.sensor_noise_model
from habitat_sim.sensors.noise_models.sensor_noise_model import SensorNoiseModel
import numpy as np
from numpy import ndarray
import typing
__all__: list[str] = ['NoSensorNoiseModel', 'SensorNoiseModel', 'SensorType', 'attr', 'ndarray', 'np', 'registry', 'torch']
class NoSensorNoiseModel(habitat_sim.sensors.noise_models.sensor_noise_model.SensorNoiseModel):
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset()
    __attrs_attrs__: typing.ClassVar[attr._make.NoSensorNoiseModelAttributes]  # value = (Attribute(name='gpu_device_id', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Optional[int], converter=None, kw_only=True, inherited=True, on_setattr=None, alias='gpu_device_id'),)
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = tuple()
    _abc_impl: typing.ClassVar[_abc._abc_data]  # value = <_abc._abc_data object>
    @staticmethod
    def is_valid_sensor_type(sensor_type: habitat_sim._ext.habitat_sim_bindings.SensorType) -> bool:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class NoSensorNoiseModel.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class NoSensorNoiseModel.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class NoSensorNoiseModel.
        """
    def __init__(self, *, gpu_device_id: typing.Optional[int] = None) -> None:
        """
        Method generated by attrs for class NoSensorNoiseModel.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class NoSensorNoiseModel.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class NoSensorNoiseModel.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class NoSensorNoiseModel.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
    def apply(self, x: typing.Union[numpy.ndarray, ForwardRef('torch.Tensor')]) -> typing.Union[numpy.ndarray, ForwardRef('torch.Tensor')]:
        ...
registry: habitat_sim.registry._Registry  # value = <habitat_sim.registry._Registry object>
torch = None
