from __future__ import annotations
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
from habitat_sim._ext.habitat_sim_bindings import SensorType
import habitat_sim.registry
import habitat_sim.sensors.noise_models.sensor_noise_model
from habitat_sim.sensors.noise_models.sensor_noise_model import SensorNoiseModel
import numpy as np
import numpy
from numpy import ndarray
import typing
__all__: list[str] = ['PoissonNoiseModel', 'PoissonNoiseModelCPUImpl', 'SensorNoiseModel', 'SensorType', 'attr', 'ndarray', 'np', 'registry']
class PoissonNoiseModel(habitat_sim.sensors.noise_models.sensor_noise_model.SensorNoiseModel):
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset()
    __attrs_attrs__: typing.ClassVar[PoissonNoiseModelAttributes]  # value = (Attribute(name='gpu_device_id', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[int, NoneType], converter=None, kw_only=True, inherited=True, on_setattr=None, alias='gpu_device_id'),)
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = tuple()
    _abc_impl: typing.ClassVar[_abc_data]  # value = <_abc_data object>
    @staticmethod
    def is_valid_sensor_type(sensor_type: habitat_sim._ext.habitat_sim_bindings.SensorType) -> bool:
        ...
    def __attrs_post_init__(self) -> None:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __init__(self, *, gpu_device_id: typing.Union[int, NoneType] = None) -> None:
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __repr__(self):
        """
        Method generated by attrs for class PoissonNoiseModel.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
    def apply(self, image: numpy.ndarray) -> numpy.ndarray:
        """
        Alias of `simulate()` to conform to base-class and expected API
        """
    def simulate(self, image: numpy.ndarray) -> numpy.ndarray:
        ...
class PoissonNoiseModelCPUImpl:
    __attrs_attrs__: typing.ClassVar[PoissonNoiseModelCPUImplAttributes]  # value = ()
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('__weakref__')
    @staticmethod
    def simulate(image: numpy.ndarray) -> numpy.ndarray:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __init__(self) -> None:
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __repr__(self):
        """
        Method generated by attrs for class PoissonNoiseModelCPUImpl.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
def _simulate(image: numpy.ndarray) -> numpy.ndarray:
    ...
registry: habitat_sim.registry._Registry  # value = <habitat_sim.registry._Registry object>
