from __future__ import annotations
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
from habitat_sim._ext.habitat_sim_bindings import SensorType
import habitat_sim.registry
import habitat_sim.sensors.noise_models.sensor_noise_model
from habitat_sim.sensors.noise_models.sensor_noise_model import SensorNoiseModel
import numba as numba
import numpy as np
import numpy
from numpy import ndarray
import posixpath as osp
import torch as torch
from torch import Tensor
import typing
__all__: list[str] = ['RedwoodDepthNoiseModel', 'RedwoodNoiseModelCPUImpl', 'SensorNoiseModel', 'SensorType', 'Tensor', 'attr', 'cuda_enabled', 'ndarray', 'np', 'numba', 'osp', 'registry', 'torch']
class RedwoodDepthNoiseModel(habitat_sim.sensors.noise_models.sensor_noise_model.SensorNoiseModel):
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset()
    __attrs_attrs__: typing.ClassVar[RedwoodDepthNoiseModelAttributes]  # value = (Attribute(name='gpu_device_id', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[int, NoneType], converter=None, kw_only=True, inherited=True, on_setattr=None, alias='gpu_device_id'), Attribute(name='noise_multiplier', default=1.0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='noise_multiplier'))
    __hash__: typing.ClassVar[None] = None
    _abc_impl: typing.ClassVar[_abc_data]  # value = <_abc_data object>
    @staticmethod
    def is_valid_sensor_type(sensor_type: habitat_sim._ext.habitat_sim_bindings.SensorType) -> bool:
        ...
    def __attrs_post_init__(self) -> None:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def __init__(self, *, gpu_device_id: typing.Union[int, NoneType] = None, noise_multiplier: float = 1.0) -> None:
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def __repr__(self):
        """
        Method generated by attrs for class RedwoodDepthNoiseModel.
        """
    def apply(self, gt_depth: typing.Union[numpy.ndarray, ForwardRef('Tensor')]) -> typing.Union[numpy.ndarray, ForwardRef('Tensor')]:
        """
        Alias of `simulate()` to conform to base-class and expected API
        """
    def simulate(self, gt_depth: typing.Union[numpy.ndarray, ForwardRef('Tensor')]) -> typing.Union[numpy.ndarray, ForwardRef('Tensor')]:
        ...
class RedwoodNoiseModelCPUImpl:
    __attrs_attrs__: typing.ClassVar[RedwoodNoiseModelCPUImplAttributes]  # value = (Attribute(name='model', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'numpy.ndarray'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='model'), Attribute(name='noise_multiplier', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='noise_multiplier'))
    __hash__: typing.ClassVar[None] = None
    def __attrs_post_init__(self):
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def __init__(self, model: numpy.ndarray, noise_multiplier: float) -> None:
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def __repr__(self):
        """
        Method generated by attrs for class RedwoodNoiseModelCPUImpl.
        """
    def simulate(self, gt_depth):
        ...
def _simulate(*args, **kwargs):
    ...
def _undistort(*args, **kwargs):
    ...
cuda_enabled: bool = False
registry: habitat_sim.registry._Registry  # value = <habitat_sim.registry._Registry object>
