from __future__ import annotations
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
from habitat_sim._ext.habitat_sim_bindings import SensorType
import habitat_sim.registry
import habitat_sim.sensors.noise_models.sensor_noise_model
from habitat_sim.sensors.noise_models.sensor_noise_model import SensorNoiseModel
import numpy as np
import numpy
from numpy import ndarray
import typing
__all__: list[str] = ['SaltAndPepperNoiseModel', 'SaltAndPepperNoiseModelCPUImpl', 'SensorNoiseModel', 'SensorType', 'attr', 'ndarray', 'np', 'registry']
class SaltAndPepperNoiseModel(habitat_sim.sensors.noise_models.sensor_noise_model.SensorNoiseModel):
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset()
    __attrs_attrs__: typing.ClassVar[SaltAndPepperNoiseModelAttributes]  # value = (Attribute(name='gpu_device_id', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[int, NoneType], converter=None, kw_only=True, inherited=True, on_setattr=None, alias='gpu_device_id'), Attribute(name='s_vs_p', default=0.5, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='s_vs_p'), Attribute(name='amount', default=0.05, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='amount'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('s_vs_p', 'amount')
    _abc_impl: typing.ClassVar[_abc_data]  # value = <_abc_data object>
    @staticmethod
    def is_valid_sensor_type(sensor_type: habitat_sim._ext.habitat_sim_bindings.SensorType) -> bool:
        ...
    def __attrs_post_init__(self) -> None:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __init__(self, *, gpu_device_id: typing.Union[int, NoneType] = None, s_vs_p: float = 0.5, amount: float = 0.05) -> None:
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __repr__(self):
        """
        Method generated by attrs for class SaltAndPepperNoiseModel.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
    def apply(self, image):
        """
        Alias of `simulate()` to conform to base-class and expected API
        """
    def simulate(self, image):
        ...
class SaltAndPepperNoiseModelCPUImpl:
    __attrs_attrs__: typing.ClassVar[SaltAndPepperNoiseModelCPUImplAttributes]  # value = (Attribute(name='s_vs_p', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='s_vs_p'), Attribute(name='amount', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='amount'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('s_vs_p', 'amount', '__weakref__')
    def __eq__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __init__(self, s_vs_p: float, amount: float) -> None:
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __repr__(self):
        """
        Method generated by attrs for class SaltAndPepperNoiseModelCPUImpl.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
    def simulate(self, image: numpy.ndarray) -> numpy.ndarray:
        ...
def _simulate(image: numpy.ndarray, s_vs_p: float, amount: float) -> numpy.ndarray:
    ...
registry: habitat_sim.registry._Registry  # value = <habitat_sim.registry._Registry object>
