from __future__ import annotations
import abc as abc
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
from habitat_sim._ext.habitat_sim_bindings import SensorType
from numpy import ndarray
import typing
__all__: list[str] = ['SensorNoiseModel', 'SensorType', 'abc', 'attr', 'ndarray']
class SensorNoiseModel(abc.ABC):
    """
    Base class for all sensor noise models
    """
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset({'is_valid_sensor_type', 'apply'})
    __attrs_attrs__: typing.ClassVar[attr._make.SensorNoiseModelAttributes]  # value = (Attribute(name='gpu_device_id', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Optional[int], converter=None, kw_only=True, inherited=False, on_setattr=None, alias='gpu_device_id'),)
    __hash__: typing.ClassVar[None] = None
    _abc_impl: typing.ClassVar[_abc._abc_data]  # value = <_abc._abc_data object>
    @staticmethod
    def is_valid_sensor_type(sensor_type: habitat_sim._ext.habitat_sim_bindings.SensorType) -> bool:
        """
        Used to determine whether or not the noise model
                is applicable to the sensor type
        
                :return: True if this noise model can be applied to this sensor input type
                
        """
    def __call__(self, sensor_observation: typing.Union[numpy.ndarray, ForwardRef('Tensor')]) -> typing.Union[numpy.ndarray, ForwardRef('Tensor')]:
        """
        Alias of `apply()`
        """
    def __eq__(self, other):
        """
        Method generated by attrs for class SensorNoiseModel.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class SensorNoiseModel.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class SensorNoiseModel.
        """
    def __init__(self, *, gpu_device_id: typing.Optional[int] = None) -> None:
        """
        Method generated by attrs for class SensorNoiseModel.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class SensorNoiseModel.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class SensorNoiseModel.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class SensorNoiseModel.
        """
    def apply(self, sensor_observation):
        """
        Applies the noise model to the sensor observation
        
                :param sensor_observation: The clean sensor observation.
                    Should not be modified.
        
                :return: The sensor observation with noise applied.
                
        """
