from __future__ import annotations
import attr as attr
import habitat_sim._ext.habitat_sim_bindings
from habitat_sim._ext.habitat_sim_bindings import SensorType
import habitat_sim.registry
import habitat_sim.sensors.noise_models.sensor_noise_model
from habitat_sim.sensors.noise_models.sensor_noise_model import SensorNoiseModel
import numpy as np
import numpy
from numpy import ndarray
import typing
__all__: list[str] = ['SensorNoiseModel', 'SensorType', 'SpeckleNoiseModel', 'SpeckleNoiseModelCPUImpl', 'attr', 'ndarray', 'np', 'registry']
class SpeckleNoiseModel(habitat_sim.sensors.noise_models.sensor_noise_model.SensorNoiseModel):
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset()
    __attrs_attrs__: typing.ClassVar[SpeckleNoiseModelAttributes]  # value = (Attribute(name='gpu_device_id', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Union[int, NoneType], converter=None, kw_only=True, inherited=True, on_setattr=None, alias='gpu_device_id'), Attribute(name='intensity_constant', default=0.2, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='intensity_constant'), Attribute(name='mean', default=0, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='mean'), Attribute(name='sigma', default=1, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='sigma'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('intensity_constant', 'mean', 'sigma')
    _abc_impl: typing.ClassVar[_abc_data]  # value = <_abc_data object>
    @staticmethod
    def is_valid_sensor_type(sensor_type: habitat_sim._ext.habitat_sim_bindings.SensorType) -> bool:
        ...
    def __attrs_post_init__(self) -> None:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __init__(self, *, gpu_device_id: typing.Union[int, NoneType] = None, intensity_constant: float = 0.2, mean: int = 0, sigma: int = 1) -> None:
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __repr__(self):
        """
        Method generated by attrs for class SpeckleNoiseModel.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
    def apply(self, image: numpy.ndarray) -> numpy.ndarray:
        """
        Alias of `simulate()` to conform to base-class and expected API
        """
    def simulate(self, image: numpy.ndarray) -> numpy.ndarray:
        ...
class SpeckleNoiseModelCPUImpl:
    __attrs_attrs__: typing.ClassVar[SpeckleNoiseModelCPUImplAttributes]  # value = (Attribute(name='intensity_constant', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'float'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='intensity_constant'), Attribute(name='mean', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='mean'), Attribute(name='sigma', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='sigma'))
    __attrs_own_setattr__: typing.ClassVar[bool] = False
    __hash__: typing.ClassVar[None] = None
    __slots__: typing.ClassVar[tuple] = ('intensity_constant', 'mean', 'sigma', '__weakref__')
    def __eq__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __ge__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __getstate__(self):
        """
        
                    Automatically created by attrs.
                    
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __init__(self, intensity_constant: float, mean: int, sigma: int) -> None:
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __ne__(self, other):
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __repr__(self):
        """
        Method generated by attrs for class SpeckleNoiseModelCPUImpl.
        """
    def __setstate__(self, state):
        """
        
                    Automatically created by attrs.
                    
        """
    def simulate(self, image: numpy.ndarray) -> numpy.ndarray:
        ...
def _simulate(image: numpy.ndarray, intensity_constant: float, mean: int, sigma: int) -> numpy.ndarray:
    ...
registry: habitat_sim.registry._Registry  # value = <habitat_sim.registry._Registry object>
