from __future__ import annotations
import attr as attr
import contextlib
from contextlib import ContextDecorator
import magnum as mn
import numpy as np
import quaternion as quaternion
import typing
__all__: list[str] = ['ContextDecorator', 'NoAttrValidationContext', 'all_is_finite', 'attr', 'is_unit_length', 'mn', 'np', 'quaternion', 'value_is_validated']
class NoAttrValidationContext(contextlib.ContextDecorator):
    """
    Ensures validators are not run within this context.
        Useful for function where we generate an attr validated object.
        
    """
    __attrs_attrs__: typing.ClassVar[attr._make.NoAttrValidationContextAttributes]  # value = (Attribute(name='original_state', default=None, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=typing.Optional[bool], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='original_state'),)
    __hash__: typing.ClassVar[None] = None
    def __enter__(self) -> NoAttrValidationContext:
        ...
    def __eq__(self, other):
        """
        Method generated by attrs for class NoAttrValidationContext.
        """
    def __exit__(self, *exc) -> None:
        ...
    def __ge__(self, other):
        """
        Method generated by attrs for class NoAttrValidationContext.
        """
    def __gt__(self, other):
        """
        Method generated by attrs for class NoAttrValidationContext.
        """
    def __init__(self, original_state: typing.Optional[bool] = None) -> None:
        """
        Method generated by attrs for class NoAttrValidationContext.
        """
    def __le__(self, other):
        """
        Method generated by attrs for class NoAttrValidationContext.
        """
    def __lt__(self, other):
        """
        Method generated by attrs for class NoAttrValidationContext.
        """
    def __ne__(self, other):
        """
        
            Check equality and either forward a NotImplemented or
            return the result negated.
            
        """
    def __repr__(self):
        """
        Method generated by attrs for class NoAttrValidationContext.
        """
def all_is_finite(instance, attribute, value) -> None:
    ...
def is_unit_length(instance, attribute, value, tol = 0.0001) -> None:
    ...
def value_is_validated(instance, attribute, value) -> None:
    ...
