"""
Root Magnum module
"""
from __future__ import annotations
from _magnum import BoolVector2
from _magnum import BoolVector3
from _magnum import BoolVector4
from _magnum import Color3
from _magnum import Color4
from _magnum import Deg
from _magnum import Image1D
from _magnum import Image2D
from _magnum import Image3D
from _magnum import ImageView1D
from _magnum import ImageView2D
from _magnum import ImageView3D
from _magnum import Matrix2x2
from _magnum import Matrix2x2d
from _magnum import Matrix2x3
from _magnum import Matrix2x3d
from _magnum import Matrix2x4
from _magnum import Matrix2x4d
from _magnum import Matrix3
from _magnum import Matrix3d
from _magnum import Matrix3x2
from _magnum import Matrix3x2d
from _magnum import Matrix3x3
from _magnum import Matrix3x3d
from _magnum import Matrix3x4
from _magnum import Matrix3x4d
from _magnum import Matrix4
from _magnum import Matrix4d
from _magnum import Matrix4x2
from _magnum import Matrix4x2d
from _magnum import Matrix4x3
from _magnum import Matrix4x3d
from _magnum import Matrix4x4
from _magnum import Matrix4x4d
from _magnum import MeshIndexType
from _magnum import MeshPrimitive
from _magnum import MutableImageView1D
from _magnum import MutableImageView2D
from _magnum import MutableImageView3D
from _magnum import PixelFormat
from _magnum import PixelStorage
from _magnum import Quaternion
from _magnum import Quaterniond
from _magnum import Rad
from _magnum import Range1D
from _magnum import Range1Dd
from _magnum import Range1Di
from _magnum import Range2D
from _magnum import Range2Dd
from _magnum import Range2Di
from _magnum import Range3D
from _magnum import Range3Dd
from _magnum import Range3Di
from _magnum import SamplerFilter
from _magnum import SamplerMipmap
from _magnum import SamplerWrapping
from _magnum import Vector2
from _magnum import Vector2d
from _magnum import Vector2i
from _magnum import Vector2ui
from _magnum import Vector3
from _magnum import Vector3d
from _magnum import Vector3i
from _magnum import Vector3ui
from _magnum import Vector4
from _magnum import Vector4d
from _magnum import Vector4i
from _magnum import Vector4ui
from _magnum import gl
from _magnum import math
from _magnum import meshtools
from _magnum import platform
from _magnum import primitives
from _magnum import scenegraph
from _magnum import shaders
from _magnum import trade
import sys as sys
__all__: list = ['Deg', 'Rad', 'BoolVector2', 'BoolVector3', 'BoolVector4', 'Vector2', 'Vector3', 'Vector4', 'Vector2d', 'Vector3d', 'Vector4d', 'Vector2i', 'Vector3i', 'Vector4i', 'Vector2ui', 'Vector3ui', 'Vector4ui', 'Color3', 'Color4', 'Matrix2x2', 'Matrix2x3', 'Matrix2x4', 'Matrix3x2', 'Matrix3x3', 'Matrix3x4', 'Matrix4x2', 'Matrix4x3', 'Matrix4x4', 'Matrix2x2d', 'Matrix2x3d', 'Matrix2x4d', 'Matrix3x2d', 'Matrix3x3d', 'Matrix3x4d', 'Matrix4x2d', 'Matrix4x3d', 'Matrix4x4d', 'Matrix3', 'Matrix4', 'Matrix3d', 'Matrix4d', 'Quaternion', 'Quaterniond', 'Range1D', 'Range1Di', 'Range1Dd', 'Range2D', 'Range2Di', 'Range2Dd', 'Range3D', 'Range3Di', 'Range3Dd', 'MeshPrimitive', 'MeshIndexType', 'PixelFormat', 'PixelStorage', 'Image1D', 'Image2D', 'Image3D', 'ImageView1D', 'ImageView2D', 'ImageView3D', 'MutableImageView1D', 'MutableImageView2D', 'MutableImageView3D', 'SamplerFilter', 'SamplerMipmap', 'SamplerWrapping']
BUILD_STATIC: bool = True
TARGET_GL: bool = True
TARGET_GLES: bool = False
TARGET_GLES2: bool = False
TARGET_VK: bool = False
TARGET_WEBGL: bool = False
i: str = 'trs'
